package vues;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.event.ListSelectionEvent;

import ressources.Competence;
import ressources.ModifEvenement;
import ressources.Personne;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class Affecter_comp extends PannelPersonnel {

   /**
    * Creates new form Ajouter_personnel
    */
   public Affecter_comp() {
	   competencescour = new Competence[1];
	   initPersonnes();
       initComponents();
       abonnerModif();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jPanel_titre = new javax.swing.JPanel();
       jLabel_Titre = new javax.swing.JLabel();
       jPanel_NPD = new javax.swing.JPanel();
       jLabel1 = new javax.swing.JLabel();
       jScrollPane3 = new javax.swing.JScrollPane();
       jListEmp = new javax.swing.JList<>();
       jPanel_LCE = new javax.swing.JPanel();
       jButton_Vali = new javax.swing.JButton();
       jPanelLC = new javax.swing.JPanel();
       jLab_comp_emp = new javax.swing.JLabel();
       jScrollPane1 = new javax.swing.JScrollPane();
       jListCompEmp = new javax.swing.JList<>();
       jPanel_boutVali = new javax.swing.JPanel();
       jButdroite = new javax.swing.JButton();
       jButdroite_tout = new javax.swing.JButton();
       jButtonguauche = new javax.swing.JButton();
       jButtonguauchetout = new javax.swing.JButton();
       jPanel_boutComp = new javax.swing.JPanel();
       jLab_liste_comp = new javax.swing.JLabel();
       jScrollPane2 = new javax.swing.JScrollPane();
       jListComp = new javax.swing.JList<>();

       jLabel_Titre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
       jLabel_Titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel_Titre.setText("Affectter des compétences");

       javax.swing.GroupLayout jPanel_titreLayout = new javax.swing.GroupLayout(jPanel_titre);
       jPanel_titre.setLayout(jPanel_titreLayout);
       jPanel_titreLayout.setHorizontalGroup(
           jPanel_titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titreLayout.createSequentialGroup()
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel_Titre, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       jPanel_titreLayout.setVerticalGroup(
           jPanel_titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titreLayout.createSequentialGroup()
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel_Titre)
               .addContainerGap())
       );

       jLabel1.setText("Choisir un employé");

       jListEmp.setModel(new javax.swing.AbstractListModel<Competence>() {
           public int getSize() { return strings.length; }
           public Competence getElementAt(int i) { return strings[i]; }
       });
       jScrollPane3.setViewportView(jListEmp);

       javax.swing.GroupLayout jPanel_NPDLayout = new javax.swing.GroupLayout(jPanel_NPD);
       jPanel_NPD.setLayout(jPanel_NPDLayout);
       jPanel_NPDLayout.setHorizontalGroup(
           jPanel_NPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel_NPDLayout.createSequentialGroup()
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(jPanel_NPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jScrollPane3))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       jPanel_NPDLayout.setVerticalGroup(
           jPanel_NPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel_NPDLayout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jLabel1)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

       jButton_Vali.setText("Valider");

       javax.swing.GroupLayout jPanel_LCELayout = new javax.swing.GroupLayout(jPanel_LCE);
       jPanel_LCE.setLayout(jPanel_LCELayout);
       jPanel_LCELayout.setHorizontalGroup(
           jPanel_LCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LCELayout.createSequentialGroup()
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jButton_Vali)
               .addGap(41, 41, 41))
       );
       jPanel_LCELayout.setVerticalGroup(
           jPanel_LCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel_LCELayout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jButton_Vali)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

       jLab_comp_emp.setText("<html> Liste des compétences <br /> de l'employé</html>");
       jLab_comp_emp.setMaximumSize(new java.awt.Dimension(200, 20));
       jLab_comp_emp.setMinimumSize(new java.awt.Dimension(200, 20));
       jLab_comp_emp.setPreferredSize(new java.awt.Dimension(200, 40));

       jListCompEmp.setModel(new javax.swing.AbstractListModel<Competence>() {
           public int getSize() { return competencescour.length; }
           public Competence getElementAt(int i) { return competencescour[i]; }
       });
       jScrollPane1.setViewportView(jListCompEmp);

       javax.swing.GroupLayout jPanelLCLayout = new javax.swing.GroupLayout(jPanelLC);
       jPanelLC.setLayout(jPanelLCLayout);
       jPanelLCLayout.setHorizontalGroup(
           jPanelLCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanelLCLayout.createSequentialGroup()
               .addGap(5, 5, 5)
               .addGroup(jPanelLCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(jLab_comp_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jScrollPane1))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       jPanelLCLayout.setVerticalGroup(
           jPanelLCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanelLCLayout.createSequentialGroup()
               .addGap(3, 3, 3)
               .addComponent(jLab_comp_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(15, Short.MAX_VALUE))
       );

       jButdroite.setLabel(">");

       jButdroite_tout.setLabel(">>");

       jButtonguauche.setLabel("<");

       jButtonguauchetout.setLabel("<<");

       javax.swing.GroupLayout jPanel_boutValiLayout = new javax.swing.GroupLayout(jPanel_boutVali);
       jPanel_boutVali.setLayout(jPanel_boutValiLayout);
       jPanel_boutValiLayout.setHorizontalGroup(
           jPanel_boutValiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel_boutValiLayout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel_boutValiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jButdroite_tout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addGroup(jPanel_boutValiLayout.createSequentialGroup()
                       .addGroup(jPanel_boutValiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jButtonguauche, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jButtonguauchetout))
                       .addGap(0, 0, Short.MAX_VALUE))
                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_boutValiLayout.createSequentialGroup()
                       .addGap(0, 0, Short.MAX_VALUE)
                       .addComponent(jButdroite, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addContainerGap())
       );
       jPanel_boutValiLayout.setVerticalGroup(
           jPanel_boutValiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel_boutValiLayout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jButdroite)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jButdroite_tout)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jButtonguauche)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jButtonguauchetout)
               .addContainerGap(20, Short.MAX_VALUE))
       );

       jLab_liste_comp.setText("<html>Liste des compétences <br /> disponibles</html>");
       jLab_liste_comp.setPreferredSize(new java.awt.Dimension(108, 20));

       jListComp.setModel(new javax.swing.AbstractListModel<Competence>() {
           
           public int getSize() { return competencescour.length; }
           public Competence getElementAt(int i) { return competencescour[i]; }
       });
       jScrollPane2.setViewportView(jListComp);

       javax.swing.GroupLayout jPanel_boutCompLayout = new javax.swing.GroupLayout(jPanel_boutComp);
       jPanel_boutComp.setLayout(jPanel_boutCompLayout);
       jPanel_boutCompLayout.setHorizontalGroup(
           jPanel_boutCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel_boutCompLayout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel_boutCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jScrollPane2)
                   .addComponent(jLab_liste_comp, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
       );
       jPanel_boutCompLayout.setVerticalGroup(
           jPanel_boutCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel_boutCompLayout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jLab_liste_comp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap())
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
       this.setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jPanel_titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
           .addComponent(jPanel_NPD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap(72, Short.MAX_VALUE)
               .addComponent(jPanelLC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jPanel_boutVali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(3, 3, 3)
               .addComponent(jPanel_boutComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(72, Short.MAX_VALUE))
           .addComponent(jPanel_LCE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addComponent(jPanel_titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jPanel_NPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(18, 18, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                       .addComponent(jPanelLC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addComponent(jPanel_boutComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                   .addComponent(jPanel_boutVali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel_LCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
       );
       jListEmp.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
           public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        	   jListEmpValueChanged(evt);
           }
       });
       jListCompEmp.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
           public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        	   jListCompEmpValueChanged(evt);
           }
       });
       jButdroite.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent evt) {
				jButdroiteActPerf(evt);
			}
       });
       jButdroite_tout.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent evt) {
				jButdroite_toutActPerf(evt);
			}
       });
       jButtonguauche.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent evt) {
				jButtonguaucheActPerf(evt);
			}
       });
       jButtonguauchetout.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent evt) {
				jButtonguauchetoutActPerf(evt);
			}
       });
   }// </editor-fold>                        


   // Variables declaration - do not modify                     
   private javax.swing.JButton jButdroite;
   private javax.swing.JButton jButdroite_tout;
   private javax.swing.JButton jButton_Vali;
   private javax.swing.JButton jButtonguauche;
   private javax.swing.JButton jButtonguauchetout;
   private javax.swing.JLabel jLab_comp_emp;
   private javax.swing.JLabel jLab_liste_comp;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel_Titre;
   private javax.swing.JList<Competence> jListCompEmp;
   private javax.swing.JList<Competence> jListComp;
   private javax.swing.JList<Personne> jListEmp;
   private javax.swing.JPanel jPanelLC;
   private javax.swing.JPanel jPanel_LCE;
   private javax.swing.JPanel jPanel_NPD;
   private javax.swing.JPanel jPanel_boutComp;
   private javax.swing.JPanel jPanel_boutVali;
   private javax.swing.JPanel jPanel_titre;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane3;
   // End of variables declaration                   
@Override
	public void reagir(ModifEvenement evt) {
		initPersonnes();
		jListEmp.setListData(personnes);
		repaint();
	}
	private void jListEmpValueChanged(ListSelectionEvent evt){
		if (!evt.getValueIsAdjusting() && jListCompEmp.getSelectedValue() != null){
			persCourante = jListEmp.getSelectedValue();
			competencescour = persCourante.getTabCompetences();
			jListCompEmp.setListData(competencescour);
			repaint();
		}
	}
	private void jListCompEmpValueChanged(ListSelectionEvent evt){
		
	}
	private void jButdroiteActPerf(ActionEvent evt){
		jListCompEmp.getSelectedValue()
	}
	private void jButdroite_toutActPerf(ActionEvent evt){
		
	}
	private void jButtonguaucheActPerf(ActionEvent evt){
		
	}
	private void jButtonguauchetoutActPerf(ActionEvent evt){
		
	}
}
