package vues;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import ressources.Competence;
import ressources.DomaineCompetences;
import ressources.ModifEvenement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author bertr
 */
public class Ajouter_personnel extends PannelPersonnel {

    /**
     * Creates new form Ajouter_personnel
     */
    public Ajouter_personnel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel_titre = new javax.swing.JPanel();
        jLabel_Titre = new javax.swing.JLabel();
        jPanel_NPD = new javax.swing.JPanel();
        jTextField_Nom = new javax.swing.JTextField();
        jTextField_prenom = new javax.swing.JTextField();
        jLabel_nom = new javax.swing.JLabel();
        jLabel_prenom = new javax.swing.JLabel();
        JLabel_date = new javax.swing.JLabel();
        jTextField_date = new javax.swing.JTextField();
        jPanel_LCE = new javax.swing.JPanel();
        jButton_Vali = new javax.swing.JButton();
        jPanelLC = new javax.swing.JPanel();
        jLab_comp_emp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel_boutVali = new javax.swing.JPanel();
        jButdroite = new javax.swing.JButton();
        jButdroite_tout = new javax.swing.JButton();
        jButtonguauche = new javax.swing.JButton();
        jButtonguauchetout = new javax.swing.JButton();
        jPanel_boutComp = new javax.swing.JPanel();
        jLab_liste_comp = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        jLabel_Titre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titre.setText("Ajouter un nouvel employé");

        javax.swing.GroupLayout jPanel_titreLayout = new javax.swing.GroupLayout(jPanel_titre);
        jPanel_titre.setLayout(jPanel_titreLayout);
        jPanel_titreLayout.setHorizontalGroup(
            jPanel_titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titreLayout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(jLabel_Titre, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel_titreLayout.setVerticalGroup(
            jPanel_titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Titre)
                .addContainerGap())
        );

        jTextField_Nom.setPreferredSize(new java.awt.Dimension(60, 20));

        jTextField_prenom.setPreferredSize(new java.awt.Dimension(60, 20));
        jTextField_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_prenomActionPerformed(evt);
            }
        });

        jLabel_nom.setText("Nom*");
        jLabel_nom.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel_prenom.setText("Prénom*");
        jLabel_prenom.setPreferredSize(new java.awt.Dimension(60, 20));

        JLabel_date.setText("Date d'entrée");
        JLabel_date.setMaximumSize(new java.awt.Dimension(80, 30));
        JLabel_date.setMinimumSize(new java.awt.Dimension(80, 30));
        JLabel_date.setPreferredSize(new java.awt.Dimension(80, 30));

        javax.swing.GroupLayout jPanel_NPDLayout = new javax.swing.GroupLayout(jPanel_NPD);
        jPanel_NPD.setLayout(jPanel_NPDLayout);
        jPanel_NPDLayout.setHorizontalGroup(
            jPanel_NPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NPDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_NPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_NPDLayout.createSequentialGroup()
                        .addGroup(jPanel_NPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel_NPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_prenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_prenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel_NPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField_date, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JLabel_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_NPDLayout.setVerticalGroup(
            jPanel_NPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NPDLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel_NPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_NPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JLabel_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton_Vali.setText("Valider");

        javax.swing.GroupLayout jPanel_LCELayout = new javax.swing.GroupLayout(jPanel_LCE);
        jPanel_LCE.setLayout(jPanel_LCELayout);
        jPanel_LCELayout.setHorizontalGroup(
            jPanel_LCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LCELayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Vali)
                .addGap(41, 41, 41))
        );
        jPanel_LCELayout.setVerticalGroup(
            jPanel_LCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LCELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Vali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLab_comp_emp.setText("<html> Liste des compétences <br /> de l'employé</html>");
        jLab_comp_emp.setMaximumSize(new java.awt.Dimension(200, 20));
        jLab_comp_emp.setMinimumSize(new java.awt.Dimension(200, 20));
        jLab_comp_emp.setPreferredSize(new java.awt.Dimension(200, 40));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanelLCLayout = new javax.swing.GroupLayout(jPanelLC);
        jPanelLC.setLayout(jPanelLCLayout);
        jPanelLCLayout.setHorizontalGroup(
            jPanelLCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLCLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelLCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLab_comp_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLCLayout.setVerticalGroup(
            jPanelLCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLCLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLab_comp_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButdroite.setLabel(">");

        jButdroite_tout.setLabel(">>");

        jButtonguauche.setLabel("<");

        jButtonguauchetout.setLabel("<<");

        javax.swing.GroupLayout jPanel_boutValiLayout = new javax.swing.GroupLayout(jPanel_boutVali);
        jPanel_boutVali.setLayout(jPanel_boutValiLayout);
        jPanel_boutValiLayout.setHorizontalGroup(
            jPanel_boutValiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_boutValiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_boutValiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButdroite_tout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_boutValiLayout.createSequentialGroup()
                        .addGroup(jPanel_boutValiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonguauche, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonguauchetout))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_boutValiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButdroite, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_boutValiLayout.setVerticalGroup(
            jPanel_boutValiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_boutValiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButdroite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButdroite_tout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonguauche)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonguauchetout)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLab_liste_comp.setText("Liste des compétences");
        jLab_liste_comp.setPreferredSize(new java.awt.Dimension(108, 20));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout jPanel_boutCompLayout = new javax.swing.GroupLayout(jPanel_boutComp);
        jPanel_boutComp.setLayout(jPanel_boutCompLayout);
        jPanel_boutCompLayout.setHorizontalGroup(
            jPanel_boutCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_boutCompLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_boutCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(jLab_liste_comp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_boutCompLayout.setVerticalGroup(
            jPanel_boutCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_boutCompLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLab_liste_comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_NPD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelLC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_boutVali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel_boutComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel_LCE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_NPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanelLC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel_boutComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel_boutVali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_LCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        //ecouteur du boutton d'ajout d'une personne
        jButton_Vali.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent evt) {
			}
        });
    
    
    }// </editor-fold>                        

    private void jTextField_prenomActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 


    // Variables declaration - do not modify                     
    private javax.swing.JLabel JLabel_date;
    private javax.swing.JButton jButdroite;
    private javax.swing.JButton jButdroite_tout;
    private javax.swing.JButton jButton_Vali;
    private javax.swing.JButton jButtonguauche;
    private javax.swing.JButton jButtonguauchetout;
    private javax.swing.JLabel jLab_comp_emp;
    private javax.swing.JLabel jLab_liste_comp;
    private javax.swing.JLabel jLabel_Titre;
    private javax.swing.JLabel jLabel_nom;
    private javax.swing.JLabel jLabel_prenom;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanelLC;
    private javax.swing.JPanel jPanel_LCE;
    private javax.swing.JPanel jPanel_NPD;
    private javax.swing.JPanel jPanel_boutComp;
    private javax.swing.JPanel jPanel_boutVali;
    private javax.swing.JPanel jPanel_titre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField_Nom;
    private javax.swing.JTextField jTextField_date;
    private javax.swing.JTextField jTextField_prenom;
    // End of variables declaration                   
	@Override
	public void reagir(ModifEvenement evt) {
		initPersonnes();
		repaint();
		
	}
}
