package vues;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import javax.swing.border.EmptyBorder;

import ressources.Competence;
import ressources.DomaineCompetences;
import ressources.ModifEvenement;

public class AjouterMiss extends PanelMissions {
	
	 /**
     * Creates new form Modifier
     */
    public AjouterMiss() {
        initMissions();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	//Le titre de la vue
    	jlab_titre = new javax.swing.JLabel();
    	//Le panel principal
        jpan_general = new javax.swing.JPanel();
        
        //Le feedback
    	jlab_feedback = new javax.swing.JLabel();
        
        //Le panel d'ajout
        jpan_ajout = new javax.swing.JPanel();
        jlab_nom = new javax.swing.JLabel();
        jtf_nom = new javax.swing.JTextField();
        jlab_nbPersonnes = new javax.swing.JLabel();
        jtf_nbPersonnes = new javax.swing.JTextField();
        jlab_dateDebut = new javax.swing.JLabel();
        jtf_dateDebut = new javax.swing.JTextField();
        jlab_duree = new javax.swing.JLabel();
        jtf_duree = new javax.swing.JTextField();
        
        jbtn_valider = new javax.swing.JButton();
        
        //Libellés
        jlab_titre.setText(TITRE);
        jlab_titre.setFont(new java.awt.Font("Tahoma", 1, 14));
        jlab_feedback.setText(FEEDBACK);
        jlab_nom.setText(jlab_nom_TEXTE);
        jlab_nbPersonnes.setText(jlab_nbPersonnes_TEXTE);
        jlab_dateDebut.setText(jlab_dateDebut_TEXTE);
        jlab_duree.setText(jlab_duree_TEXTE);
        
        //Bouton
        jbtn_valider.setText(jbtn_valider_TEXTE);
        
        //Layout
        this.setLayout(new BorderLayout(20, 20));
        this.add(jlab_titre, BorderLayout.NORTH);
        this.add(jpan_general, BorderLayout.CENTER);
        
        jpan_general.setLayout(new BorderLayout(20, 20));
        jpan_general.add(jlab_feedback, BorderLayout.NORTH);
        jpan_general.add(jpan_ajout, BorderLayout.CENTER);
        jpan_general.setBorder(new EmptyBorder(10, 20, 20, 20));
        
        jpan_ajout.setLayout(new GridLayout(5, 2));
        jpan_ajout.add(jlab_nom);
        jpan_ajout.add(jtf_nom);
        jpan_ajout.add(jlab_nbPersonnes);
        jpan_ajout.add(jtf_nbPersonnes);
        jpan_ajout.add(jlab_dateDebut);
        jpan_ajout.add(jtf_dateDebut);
        jpan_ajout.add(jlab_duree);
        jpan_ajout.add(jtf_duree);
        jpan_ajout.add(jbtn_valider);
       
        jbtn_valider.setMinimumSize(new Dimension(180, 15));
        
        //Ecouteurs d'événement
        jbtn_valider.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent evt) {
				jbtn_validerActPerf(evt);
			}
        });
    }
        
	
	@Override
	public void reagir(ModifEvenement evt) {
		// TODO Auto-generated method stub

	}
	
	// Variables declaration - do not modify                     
    private javax.swing.JLabel jlab_titre;
    private javax.swing.JPanel jpan_general;
    private javax.swing.JLabel jlab_feedback;
    
    private javax.swing.JPanel jpan_ajout;
    private javax.swing.JLabel jlab_nom;
    private javax.swing.JTextField jtf_nom;
    private javax.swing.JLabel jlab_nbPersonnes;
    private javax.swing.JTextField jtf_nbPersonnes;
    private javax.swing.JLabel jlab_dateDebut;
    private javax.swing.JTextField jtf_dateDebut;
    private javax.swing.JLabel jlab_duree;
    private javax.swing.JTextField jtf_duree;
    javax.swing.JButton jbtn_valider;
    
    //Libellés
    private final String TITRE = "Ajouter une mission";
    private final String FEEDBACK = "";
    private final String jlab_nom_TEXTE = "Nom de la mission : ";
    private final String jlab_nbPersonnes_TEXTE = "Nombre de personnes : ";
    private final String jlab_dateDebut_TEXTE = "Date de début (jj/MM/aaaa) : ";
    private final String jlab_duree_TEXTE = "Durée en nombre de jours : ";
    private final String jbtn_valider_TEXTE = "Valider";

    //Gestiond des événements
    public void jbtn_validerActPerf(ActionEvent evt){
    	if (jtf_nom.getText().trim().equals("")){
    		jlab_feedback.setText("Ajoutez un nom pour la nouvelle mission.");
    		
    	} else if (jtf_nbPersonnes.getText().trim().equals("")) {
    		jlab_feedback.setText("Définisez le nombre de personnes pour la mission.");
    		
    	} else if (jtf_dateDebut.getText().trim().equals("")) {
    		jlab_feedback.setText("Définisez la date de début de la mission.");
    		
    	} else if (jtf_duree.getText().trim().equals("")) {
    		jlab_feedback.setText("Définisez la duree de la mission.");
    		
    	} else {
    		/*ajouter(new Mission((DomaineCompetences) jtf_nom.getText(), jtf_libelleFR.getText()));
	    	jtf_libelleGB.setText(libGB_TEXTE);
	        jtf_libelleFR.setText(libFR_TEXTE);
	        jcombo_domaines.setSelectedItem(DomaineCompetences.UNDEFINED);*/
	        jlab_feedback.setText("La nouvelle compétence a bien été joutée à la liste. Veuillez vérifier la liste des compétences.");
    	}
    	
    	this.repaint();
    }
}
