package vues;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;

import reader_writer.EcriteurCompetences;
import reader_writer.IHMCompetencesAccessor;
import reader_writer.LecteurCompetences;
import ressources.Competence;
import ressources.DomaineCompetences;
import ressources.IModifEcouteur;
import ressources.ListeCompetences;
import ressources.ModifEvenement;

public class Listecpt2 extends javax.swing.JPanel implements IModifEcouteur{

    /**
     * Creates new form Listecpt
     */
    public Listecpt2() {
    	initCompetences();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	//Le titre de la vue
        jlab_titre = new javax.swing.JLabel();
        //Le panel principal
        jpan_general = new javax.swing.JPanel();
        
        //Le panel proposant des options de tri
        jpan_tri = new javax.swing.JPanel();
        //Le champ de texte destiné à la recherche par libellé
        jtf_rechercheParLib = new javax.swing.JTextField();
        //Bouton de recherche par libellé (est-il utile?)
        jbtn_rehcercher = new javax.swing.JButton();
        //Bouton de supression des paramètres de tri
        jbtn_toutes = new javax.swing.JButton();
        //Bouton d'enrégistrement de la liste
        jbtn_enregistrer = new javax.swing.JButton();
        //Libellé de la recherche par domaine
        jlab_triDomaine = new javax.swing.JLabel();
        //Combo box qui affiche le choix de domaine
        jcombo_domaines = new javax.swing.JComboBox(DOMAINES);
        //Libellé de la recherche par code
        jlab_triCode = new javax.swing.JLabel();
        //Text field permettant d'insérer le numéro de code
        jtf_code = new javax.swing.JTextField();
        
        //Le scroll panel contenant la liste des compétences
        jscroll_listeCompetences = new javax.swing.JScrollPane();
        //La liste des copétences
        jlist_competences = new javax.swing.JList<Competence>();
        
        jlab_titre.setText(TITRE);
        
        //Libellés
        jtf_rechercheParLib.setText(rechercheParLib_TEXTE);
        jlab_triDomaine.setText(trieParDomaine_TEXTE);
        jlab_triCode.setText(trieParCode_TEXTE);
        
        //Boutons
        jbtn_rehcercher.setText(btnRechercher_TEXTE);
        jbtn_toutes.setText(btnToutes_TEXTE);
        jbtn_enregistrer.setText(btnEnregistrer_TEXTE);
        
        //Combo box
        jcombo_domaines.setSelectedItem(DomaineCompetences.UNDEFINED);
        
        this.setLayout(new BorderLayout(20, 20));
        this.add(jlab_titre, BorderLayout.NORTH);
        this.add(jpan_general, BorderLayout.CENTER);
        
        jpan_general.setLayout(new BorderLayout(20, 20));
        jpan_general.add(jpan_tri, BorderLayout.NORTH);
        jpan_general.add(jscroll_listeCompetences, BorderLayout.CENTER);
        jpan_general.setBorder(new EmptyBorder(10, 20, 20, 20));
        
        jpan_tri.setName(jpan_tri_NAME);
        jpan_tri.setLayout(new GridLayout(4, 2, 15, 10));
        jpan_tri.setBorder(new EmptyBorder(10, 0, 10, 180));
        
        jpan_tri.add(jlab_triDomaine);
        jpan_tri.add(jcombo_domaines);
        jpan_tri.add(jlab_triCode);
        jpan_tri.add(jtf_code);
        jpan_tri.add(jtf_rechercheParLib);
        jpan_tri.add(jbtn_rehcercher);
        jpan_tri.add(jbtn_toutes);
        jpan_tri.add(jbtn_enregistrer);
        
        // Liste
        jlist_competences.setModel(new javax.swing.AbstractListModel<Competence>() {
            public int getSize() { return competences.length; }
            public Competence getElementAt(int i) { return competences[i]; }
        });
        
        jlist_competences.setListData(competences);
        
        jscroll_listeCompetences.setViewportView(jlist_competences);
        
        // Ajout des écouteurs d'événement
        jbtn_rehcercher.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent evt) {
				jbtn_rehcercherActPerf(evt);
			}
        });
        
        jcombo_domaines.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent evt) {
				jcombo_selectedActPerf(evt);
			}
        });
        
        jbtn_toutes.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent evt) {
				jbtn_toutesActPerf(evt);
			}
        });
        
        jtf_code.addKeyListener(new KeyAdapter(){
			@Override
			public void keyTyped(KeyEvent evt) {
				jtf_codeKeyTyped(evt);
			}
        	
        });
        
        
        jbtn_enregistrer.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent evt) {
				jbtn_enregistrerActPerf(evt);
			}
        });
        
        //ajouter à la liste des ecouteurs de modification de la liste des compétences
        IHMCompetencesAccessor.addModifEcouteur(this);
        
    }// </editor-fold>                        

    private void initCompetences(){
    	competences = IHMCompetencesAccessor.competences_init.getTab();
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel jlab_titre;
    private javax.swing.JPanel jpan_general;
    
    private javax.swing.JPanel jpan_tri;
    private javax.swing.JButton jbtn_rehcercher;
    private javax.swing.JButton jbtn_toutes;
    private javax.swing.JButton jbtn_enregistrer;
    private javax.swing.JTextField jtf_rechercheParLib;
    private javax.swing.JLabel jlab_triDomaine;
    private javax.swing.JComboBox jcombo_domaines;
    private javax.swing.JLabel jlab_triCode;
    private javax.swing.JTextField jtf_code;
    
    private javax.swing.JList<Competence> jlist_competences;
    private javax.swing.JScrollPane jscroll_listeCompetences;    
    
    //Libellés
    private final String TITRE = "Liste des compétences";
    private final String rechercheParLib_TEXTE = "Rehcerche par mot clé...";
    private final String trieParDomaine_TEXTE = "Trier par domaine :";
    private final String trieParCode_TEXTE = "Trier par code :";
    private final String btnRechercher_TEXTE = "Rechercher";
    private final String btnToutes_TEXTE = "Toutes les compétences";
    private final String btnEnregistrer_TEXTE = "Enrégistrer la liste";
    private final String jpan_tri_NAME = "Trier la liste";
    
    private Competence[] competences;
    
    private final DomaineCompetences[] DOMAINES = DomaineCompetences.values();
    private int codeCpt = 0;
    // End of variables declaration
    
    //Réacion à l'appuyi sur le bouton rechercher
    public void jbtn_rehcercherActPerf(ActionEvent evt){
    	jtf_code.setText("");
    	if (jtf_rechercheParLib.getText().trim().equals("")) {
    		jtf_rechercheParLib.setText(rechercheParLib_TEXTE);
    		initCompetences();
    		jlist_competences.setListData(competences);
    	} else {
    		competences = IHMCompetencesAccessor.competences_init.get(jtf_rechercheParLib.getText()).getTab();
    		jlist_competences.setListData(competences);
    	}
    	this.repaint();
    }
    
    //Réaction à la selection d'un domaine à partir de la liste déroulante
    public void jcombo_selectedActPerf(ActionEvent evt){
    	jtf_rechercheParLib.setText(rechercheParLib_TEXTE);
    	jtf_code.setText("");
    	competences = IHMCompetencesAccessor.competences_init.get((DomaineCompetences) jcombo_domaines.getSelectedItem()).getTab();
    	jlist_competences.setListData(competences);
    	this.repaint();
    }
    
    //Réaction à l'apuyi sur le bouton toutes les compétences
    public void jbtn_toutesActPerf(ActionEvent evt){
    	jtf_rechercheParLib.setText(rechercheParLib_TEXTE);
    	jtf_code.setText("");
    	jcombo_domaines.setSelectedItem(DomaineCompetences.UNDEFINED);
    	initCompetences();
    	jlist_competences.setListData(competences);
    	this.repaint();
    }
    
    //Réation de l'appuyi sur une touche clavier pour le champ code
    //prend en compte les valeurs entre 0 et 99
    public void jtf_codeKeyTyped(KeyEvent evt){
    	jtf_rechercheParLib.setText(rechercheParLib_TEXTE);
    	
    	if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
    		//System.out.println(evt.getKeyChar()); //debug
    		codeCptMAJ(Character.getNumericValue(evt.getKeyChar()));
    		competences = IHMCompetencesAccessor.competences_init.get(codeCpt).getTab();
    		jlist_competences.setListData(competences);
    		
    		if(jtf_code.getText().length() == 2){
    			jtf_code.setText("");
    		}
    		
    	} else {
    		jtf_code.setText("");
    		codeCptINIT();
    	}
    	this.repaint();
    }
    
    public void codeCptMAJ(int characterNumericValue) {
    	if (codeCpt*10 >= 100) {
    		codeCpt = characterNumericValue;
    	} else {
    		codeCpt *= 10;
    		codeCpt += characterNumericValue;
    	}
    }
    
    public void codeCptINIT(){
    	codeCpt = 0;
    }
    
    //Enrégistrement de la liste
    public void jbtn_enregistrerActPerf(ActionEvent evt){
    	IHMCompetencesAccessor.EC.ecrireCompetences(IHMCompetencesAccessor.competences_init);
    	this.repaint();
    }
    
    @Override
    public void reagir(ModifEvenement evt){
    	initCompetences();
    	jlist_competences.setListData(competences);
    }
}
