package vues;

import java.awt.BorderLayout;
import java.awt.GridLayout;

import javax.swing.border.EmptyBorder;

import missions.Mission;
import ressources.Competence;
import ressources.DomaineCompetences;
import ressources.ModifEvenement;

public class ListeMiss extends PanelMissions{
	 /**
     * Creates new form Listecpt
     */
    public ListeMiss() {
    	initMissions();
        initComponents();
      //ajouter à la liste des ecouteurs de modification de la liste des compétences
        abonnerModif();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	//Le titre de la vue
        jlab_titre = new javax.swing.JLabel();
        //Le panel principal
        jpan_general = new javax.swing.JPanel();
        
        //Le scroll panel contenant la liste des compétences
        jscroll_listeMissions = new javax.swing.JScrollPane();
        //La liste des copétences
        jlist_missions = new javax.swing.JList<Mission>();
        
        jlab_titre.setText(TITRE);
        jlab_titre.setFont(new java.awt.Font("Tahoma", 1, 14));
        
        
        this.setLayout(new BorderLayout(20, 20));
        this.add(jlab_titre, BorderLayout.NORTH);
        this.add(jpan_general, BorderLayout.CENTER);
        
        jpan_general.setLayout(new BorderLayout(20, 20));
        jpan_general.add(jscroll_listeMissions, BorderLayout.CENTER);
        jpan_general.setBorder(new EmptyBorder(10, 20, 20, 20));
        
        // Liste
        jlist_missions.setModel(new javax.swing.AbstractListModel<Mission>() {
            public int getSize() { return missions.length; }
            public Mission getElementAt(int i) { return missions[i]; }
        });
        
        jlist_missions.setListData(missions);
        
        jscroll_listeMissions.setViewportView(jlist_missions);
    }
	
	// Variables declaration - do not modify
    private javax.swing.JLabel jlab_titre;
    private javax.swing.JPanel jpan_general;
    
    private javax.swing.JList<Mission> jlist_missions;
    private javax.swing.JScrollPane jscroll_listeMissions;    
    
    //Libellés
    private final String TITRE = "Liste des missions";
    
	@Override
	public void reagir(ModifEvenement evt) {
		initMissions();
		jlist_missions.setListData(missions);
		repaint();
	}

}
