package vues;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;

import reader_writer.LecteurCompetences;
import ressources.Competence;
import ressources.DomaineCompetences;
import ressources.ListeCompetences;

public class Listecpt2 extends javax.swing.JPanel {

    /**
     * Creates new form Listecpt
     */
    public Listecpt2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	//Le titre de la vue
        jlab_titre = new javax.swing.JLabel();
        //Le panel principal
        jpan_general = new javax.swing.JPanel();
        
        //Le panel proposant des options de tri
        jpan_tri = new javax.swing.JPanel();
        //Le champ de texte destiné à la recherche par libellé
        jtf_rechercheParLib = new javax.swing.JTextField();
        //Bouton de recherche par libellé (est-il utile?)
        jbtn_rehcercher = new javax.swing.JButton();
        //Bouton de supression des paramètres de tri
        jbtn_toutes = new javax.swing.JButton();
        //Libellé de la recherche par domaine
        jlab_triDomaine = new javax.swing.JLabel();
        //Combo box qui affiche le choix de domaine
        jcombo_domaines = new javax.swing.JComboBox(DOMAINES);
        //Libellé de la recherche par code
        jlab_triCode = new javax.swing.JLabel();
        //Text field permettant d'insérer le numéro de code
        jtf_code = new javax.swing.JTextField();
        
        //Le scroll panel contenant la liste des compétences
        jscroll_listeCompetences = new javax.swing.JScrollPane();
        //La liste des copétences
        jlist_competences = new javax.swing.JList<Competence>();
        
        jlab_titre.setText("Liste des compétence");
        
        //Libellés
        jtf_rechercheParLib.setText(rechercheParLib_TEXTE);
        jlab_triDomaine.setText("Trier par domaine : ");
        jlab_triCode.setText("Trier par code : ");
        
        //Boutons
        jbtn_rehcercher.setText("Rechercher");
        jbtn_toutes.setText("Toutes les compétences");
        
        this.setLayout(new BorderLayout(20, 20));
        this.add(jlab_titre, BorderLayout.NORTH);
        this.add(jpan_general, BorderLayout.CENTER);
        
        jpan_general.setLayout(new BorderLayout(20, 20));
        jpan_general.add(jpan_tri, BorderLayout.NORTH);
        jpan_general.add(jscroll_listeCompetences, BorderLayout.CENTER);
        jpan_general.setBorder(new EmptyBorder(10, 20, 20, 20));
        
        jpan_tri.setName("Trier la liste");
        jpan_tri.setLayout(new GridLayout(4, 2, 15, 10));
        jpan_tri.setBorder(new EmptyBorder(10, 0, 10, 180));
        
        jpan_tri.add(jlab_triDomaine);
        jpan_tri.add(jcombo_domaines);
        jpan_tri.add(jlab_triCode);
        jpan_tri.add(jtf_code);
        jpan_tri.add(jtf_rechercheParLib);
        jpan_tri.add(jbtn_rehcercher);
        jpan_tri.add(jbtn_toutes);
        
        jlist_competences.setModel(new javax.swing.AbstractListModel<Competence>() {
            public int getSize() { return competences.length; }
            public Competence getElementAt(int i) { return competences[i]; }
        });
        
        jscroll_listeCompetences.setViewportView(jlist_competences);
        
        // Ajout des écouteurs d'événement
        jbtn_rehcercher.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent evt) {
				jbtn_rehcercherActPerf(evt);
			}
        });
        
        jcombo_domaines.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent evt) {
				jcombo_selectedActPerf(evt);
			}
        });
        
        jbtn_toutes.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent evt) {
				jbtn_toutesActPerf(evt);
			}
        });
        
        jtf_code.addKeyListener(new KeyAdapter(){
			@Override
			public void keyTyped(KeyEvent evt) {
				jtf_codeKeyTyped(evt);
			}
        	
        });
        //javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        //this.setLayout(layout);
        /*layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jscroll_listeCompetences, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jtf_rechercheParLib, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68)
                            .addComponent(jbtn_rehcercher, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                        .addComponent(jlab_titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );*/
        /*layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jlab_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_rechercheParLib)
                    .addComponent(jbtn_rehcercher, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(jscroll_listeCompetences, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );*/
    }// </editor-fold>                        


    // Variables declaration - do not modify
    private javax.swing.JLabel jlab_titre;
    private javax.swing.JPanel jpan_general;
    
    private javax.swing.JPanel jpan_tri;
    private javax.swing.JButton jbtn_rehcercher;
    private javax.swing.JButton jbtn_toutes;
    private javax.swing.JTextField jtf_rechercheParLib;
    private final String rechercheParLib_TEXTE = "Rehcerche par mot clé...";
    private javax.swing.JLabel jlab_triDomaine;
    private javax.swing.JComboBox jcombo_domaines;
    private javax.swing.JLabel jlab_triCode;
    private javax.swing.JTextField jtf_code;
    
    private javax.swing.JList<Competence> jlist_competences;
    private javax.swing.JScrollPane jscroll_listeCompetences;
    
    private final LecteurCompetences LC = LecteurCompetences.Instance();
    private final ListeCompetences COMPETENCES_INIT = LC.lireCompetences();
    private Competence[] competences = COMPETENCES_INIT.getTab();
    
    private final DomaineCompetences[] DOMAINES = DomaineCompetences.values();
    // End of variables declaration
    
    //Réacion à l'appuyi sur le bouton rechercher
    public void jbtn_rehcercherActPerf(ActionEvent evt){
    	jtf_code.setText("");
    	if (jtf_rechercheParLib.getText().trim().equals("")) {
    		jtf_rechercheParLib.setText(rechercheParLib_TEXTE);
    		competences = COMPETENCES_INIT.getTab();
    	} else {
    		competences = COMPETENCES_INIT.get(jtf_rechercheParLib.getText()).getTab();
    	}
    	this.repaint();
    }
    
    //Réaction à la selection d'un domaine à partir de la liste déroulante
    public void jcombo_selectedActPerf(ActionEvent evt){
    	jtf_rechercheParLib.setText(rechercheParLib_TEXTE);
    	jtf_code.setText("");
    	competences = COMPETENCES_INIT.get((DomaineCompetences) jcombo_domaines.getSelectedItem()).getTab();
    	this.repaint();
    }
    
    //Réaction à l'apuyi sur le bouton toutes les compétences
    public void jbtn_toutesActPerf(ActionEvent evt){
    	jtf_rechercheParLib.setText(rechercheParLib_TEXTE);
    	jtf_code.setText("");
    	jcombo_domaines.setSelectedItem(DomaineCompetences.UNDEFINED);
    	competences = COMPETENCES_INIT.getTab();
    	this.repaint();
    }
    
    //Réation de l'appuyi sur une touche clavier pour le champ code
    //pend en compte les valeurs entre 0 et 9
    //TODO valeurs de deux chiffres (10, 11, 12 etc.)
    public void jtf_codeKeyTyped(KeyEvent evt){
    	jtf_rechercheParLib.setText(rechercheParLib_TEXTE);
    	if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
    		System.out.println(evt.getKeyChar());
    		competences = COMPETENCES_INIT.get(Character.getNumericValue(evt.getKeyChar())).getTab();
    	}
    	jtf_code.setText("");
    	this.repaint();
    }
}
