package vues;

import javax.swing.JList;

import ressources.Competence;
import ressources.ModifEvenement;

public class Modifier2 extends PanelCompetences {

    /**
     * Creates new form Modifier
     */
    public Modifier2() {
    	initCompetences();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jlab_titre = new javax.swing.JLabel();
        jscroll_competences = new javax.swing.JScrollPane();
        jlist_competences = new javax.swing.JList<Competence>();
        jlab_libFR = new javax.swing.JLabel();
        jtf_libFR = new javax.swing.JTextField();
        jlab_libGB = new javax.swing.JLabel();
        jtf_libGB = new javax.swing.JTextField();
        jbtn_valider = new javax.swing.JButton();

        jlab_titre.setText(TITRE);

        jlist_competences.setModel(new javax.swing.AbstractListModel<Competence>() {
           public int getSize() { return competences.length; }
           public Competence getElementAt(int i) { return competences[i]; }
        });
        
        jlist_competences.setListData(competences);
        
        jscroll_competences.setViewportView(jlist_competences);

        jlab_libFR.setText(libFR_TEXTE);

        jtf_libFR.setText(VIDE);

        jlab_libGB.setText(libGB_TEXTE);

        jtf_libGB.setText(VIDE);

        jbtn_valider.setText(valider_TEXTE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtn_valider)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlab_titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jscroll_competences, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addGap(18, 25, Short.MAX_VALUE)
                        .addContainerGap(192, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_libGB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlab_libGB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlab_libFR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_libFR, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlab_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jscroll_competences, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE))
                                .addGap(7, 7, 7))
                        .addGap(32, 32, 32)))
                .addComponent(jlab_libFR, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_libFR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlab_libGB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_libGB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jbtn_valider)
                .addContainerGap())
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton jbtn_valider;
    private javax.swing.JLabel jlab_titre;
    private javax.swing.JLabel jlab_libFR;
    private javax.swing.JLabel jlab_libGB;
    private JList<Competence> jlist_competences;
    private javax.swing.JScrollPane jscroll_competences;
    private javax.swing.JTextField jtf_libFR;
    private javax.swing.JTextField jtf_libGB;
    
    private final String libFR_TEXTE = "Libelé en Francais";
    private final String VIDE = "";
    private final String libGB_TEXTE = "Libelé en Anglais";
    private final String valider_TEXTE = "Valider";
    private final String TITRE = "Modifier la compétence";
   
    // End of variables declaration 
    
	@Override
	
	public void reagir(ModifEvenement evt) {
		initCompetences();
    	jlist_competences.setListData(competences);
	}
                      
}

