package vues;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.JList;
import javax.swing.LayoutStyle;
import javax.swing.border.EmptyBorder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import ressources.Competence;
import ressources.ModifEvenement;

public class Modifier2 extends PanelCompetences {

    /**
     * Creates new form Modifier
     */
    public Modifier2() {
    	initCompetences();
        initComponents();
        //ajouter à la liste des ecouteurs de modification de la liste des compétences
        abonnerModif();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jlab_titre = new javax.swing.JLabel();
        jpan_general = new javax.swing.JPanel();
        jpan_options = new javax.swing.JPanel();
        jpan_competences = new javax.swing.JPanel(); 
        
        jlab_competences = new javax.swing.JLabel();
        jscroll_competences = new javax.swing.JScrollPane();
        jlist_competences = new javax.swing.JList<Competence>();
        jlab_libFR = new javax.swing.JLabel();
        jtf_libFR = new javax.swing.JTextField();
        jlab_libGB = new javax.swing.JLabel();
        jtf_libGB = new javax.swing.JTextField();
        jbtn_valider = new javax.swing.JButton();        
        
        
        //
        jlab_titre.setText(TITRE);
        jlab_titre.setFont(new java.awt.Font("Tahoma", 1, 14));
        
        jlist_competences.setModel(new javax.swing.AbstractListModel<Competence>() {
           public int getSize() { return competences.length; }
           public Competence getElementAt(int i) { return competences[i]; }
        });
                
        jlist_competences.setListData(competences);
        
        jscroll_competences.setViewportView(jlist_competences);
        
        jlab_competences.setText(competences_TEXTE);

        jlab_libFR.setText(libFR_TEXTE);

        jtf_libFR.setText(VIDE);
        jtf_libGB.setMaximumSize(new Dimension(300, 15));
        
        jlab_libGB.setText(libGB_TEXTE);

        jtf_libGB.setText(VIDE);
        jtf_libGB.setMaximumSize(new Dimension(300, 15));
        
        jbtn_valider.setText(valider_TEXTE);
        
      
        //Layout
        jpan_competences.setLayout(new BorderLayout(20, 20));
        jpan_competences.add(jlab_competences, BorderLayout.NORTH);
        jpan_competences.add(jscroll_competences, BorderLayout.CENTER);
        
        GroupLayout layoutOptions = new GroupLayout(jpan_options);
        jpan_options.setLayout(layoutOptions);
        
        layoutOptions.setVerticalGroup(
        		layoutOptions.createSequentialGroup()
        			.addComponent(jlab_libGB, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		           .addComponent(jtf_libGB, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		           .addComponent(jlab_libFR, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		           .addComponent(jtf_libFR, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		           .addComponent(jbtn_valider, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		           .addGap(400)
     	);
        
        layoutOptions.setHorizontalGroup(
        		layoutOptions.createParallelGroup()
		           .addComponent(jlab_libGB, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		           .addComponent(jtf_libGB, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		           .addComponent(jlab_libFR, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		           .addComponent(jtf_libFR, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		           .addComponent(jbtn_valider, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
        
        jbtn_valider.setMinimumSize(new Dimension(180, 15));
        
        jpan_general.setLayout(new GridLayout(1, 2, 20, 20));
        jpan_general.add(jpan_competences);
        jpan_general.add(jpan_options);
        jpan_general.setBorder(new EmptyBorder(10, 20, 20, 20));
        

        this.setLayout(new BorderLayout(20, 20));
        this.add(jlab_titre, BorderLayout.NORTH);
        this.add(jpan_general, BorderLayout.CENTER);
        
      //Ecouteurs d'événement
        jlist_competences.addListSelectionListener(new ListSelectionListener(){

			@Override
			public void valueChanged(ListSelectionEvent e) {
				jlist_competencesVelueChanged(e);
			}
        	
        });
        jbtn_valider.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent evt) {
				jbtn_validerActPerf(evt);
			}
        });

        
    }// </editor-fold>                        


    // Variables declaration - do not modify  
    private javax.swing.JLabel jlab_titre;
    private javax.swing.JPanel jpan_general;
    private javax.swing.JPanel jpan_options;
    private javax.swing.JPanel jpan_competences;
    
    private javax.swing.JLabel jlab_competences;
    private JList<Competence> jlist_competences;
    private javax.swing.JScrollPane jscroll_competences;
    
    private javax.swing.JLabel jlab_libFR;
    private javax.swing.JLabel jlab_libGB;
    private javax.swing.JTextField jtf_libFR;
    private javax.swing.JTextField jtf_libGB;
    
    private javax.swing.JButton jbtn_valider;
    
    private final String competences_TEXTE = "Liste des compétences";
    private final String libFR_TEXTE = "Libelé en Francais";
    private final String VIDE = "";
    private final String libGB_TEXTE = "Libelé en Anglais";
    private final String valider_TEXTE = "Valider";
    private final String TITRE = "Modifier la compétence";
   
    // End of variables declaration 
    
	@Override
	
	public void reagir(ModifEvenement evt) {
		initCompetences();
    	jlist_competences.setListData(competences);
	}
	
	// Gestion des événements
	// Sélection d'un élément de la liste des competences
	public void jlist_competencesVelueChanged(ListSelectionEvent e){
		if (!e.getValueIsAdjusting()) {
			//cptCourante = jlist_competences.getSelectedValue();
			jtf_libFR.setText(jlist_competences.getSelectedValue().getLibFR());
			jtf_libGB.setText(jlist_competences.getSelectedValue().getLibGB());
			this.repaint();
		}
	}
	
	public void jbtn_validerActPerf(ActionEvent evt){
		jlist_competences.getSelectedValue().setLibFR(jtf_libFR.getText());
		jlist_competences.getSelectedValue().setLibGB(jtf_libGB.getText());
		this.repaint();
	}
                      
}

